#ifndef COLOR
#define COLOR

#define USE_COLOR

#define ANSI_COLOR_RESET             "\x1b[0m"
#define ANSI_COLOR_WHITE_BOLD        "\x1b[1m"
#define ANSI_COLOR_DARK_GRAY         "\x1b[2m"
#define ANSI_COLOR_ITALICS           "\x1b[3m"
#define ANSI_COLOR_UNDERLINE         "\x1b[4m"
#define ANSI_COLOR_BACKLIT           "\x1b[7m"
#define ANSI_COLOR_INVIS             "\x1b[8m"
#define ANSI_COLOR_STRIKE            "\x1b[9m"

#define ANSI_COLOR_DOUBLE_UNDERLINE  "\x1b[21m"

#define ANSI_COLOR_GRAY              "\x1b[30m"
#define ANSI_COLOR_RED               "\x1b[31m"
#define ANSI_COLOR_GREEN             "\x1b[32m"
#define ANSI_COLOR_YELLOW            "\x1b[33m"
#define ANSI_COLOR_BLUE              "\x1b[34m"
#define ANSI_COLOR_MAGENTA           "\x1b[35m"
#define ANSI_COLOR_CYAN              "\x1b[36m"
#define ANSI_COLOR_WHITE             "\x1b[37m"

#define ANSI_COLOR_BACKLIT_BLACK     "\x1b[40m"
#define ANSI_COLOR_BACKLIT_RED       "\x1b[41m"
#define ANSI_COLOR_BACKLIT_GREEN     "\x1b[42m"
#define ANSI_COLOR_BACKLIT_YELLOW    "\x1b[43m"
#define ANSI_COLOR_BACKLIT_BLUE      "\x1b[44m"
#define ANSI_COLOR_BACKLIT_MAGENTA   "\x1b[45m"
#define ANSI_COLOR_BACKLIT_CYAN      "\x1b[46m"
#define ANSI_COLOR_BACKLIT_WHITE     "\x1b[47m"

#ifdef USE_COLOR

#define RESET ANSI_COLOR_RESET
#define WHITE_BOLD ANSI_COLOR_WHITE_BOLD
#define DARK_GRAY ANSI_COLOR_DARK_GRAY
#define ITALICS ANSI_COLOR_ITALICS
#define UNDERLINE ANSI_COLOR_UNDERLINE
#define BACKLIT ANSI_COLOR_BACKLIT
#define INVIS ANSI_COLOR_INVIS
#define STRIKE ANSI_COLOR_STRIKE
#define DOUBLE_UNDERLINE ANSI_COLOR_DOUBLE_UNDERLINE
#define GRAY ANSI_COLOR_GRAY
#define RED ANSI_COLOR_RED
#define GREEN ANSI_COLOR_GREEN
#define YELLOW ANSI_COLOR_YELLOW
#define BLUE ANSI_COLOR_BLUE
#define MAGENTA ANSI_COLOR_MAGENTA
#define CYAN ANSI_COLOR_CYAN
#define WHITE ANSI_COLOR_WHITE
#define BACKLIT_BLACK ANSI_COLOR_BACKLIT_BLACK
#define BACKLIT_RED ANSI_COLOR_BACKLIT_RED
#define BACKLIT_GREEN ANSI_COLOR_BACKLIT_GREEN
#define BACKLIT_YELLOW ANSI_COLOR_BACKLIT_YELLOW
#define BACKLIT_BLUE ANSI_COLOR_BACKLIT_BLUE
#define BACKLIT_MAGENTA ANSI_COLOR_BACKLIT_MAGENTA
#define BACKLIT_CYAN ANSI_COLOR_BACKLIT_CYAN
#define BACKLIT_WHITE ANSI_COLOR_BACKLIT_WHITE
#else
#define RESET
#define WHITE_BOLD
#define DARK_GRAY
#define ITALICS
#define UNDERLINE
#define BACKLIT
#define INVIS
#define STRIKE
#define DOUBLE_UNDERLINE
#define GRAY
#define RED
#define GREEN
#define YELLOW
#define BLUE
#define MAGENTA
#define CYAN
#define WHITE
#define BACKLIT_BLACK
#define BACKLIT_RED
#define BACKLIT_GREEN
#define BACKLIT_YELLOW
#define BACKLIT_BLUE
#define BACKLIT_MAGENTA
#define BACKLIT_CYAN
#define BACKLIT_WHITE
#endif

#endif
